[package]
name = "audio-ut"
version = "1.0.0"
authors = ["Thomas Büning <buening@online.de>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.2.3"
gettext-rs = "0.7"
cstr = "0.2.8"
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"
